export const results = {
	start: 20,
	numberfound: 82,
	results: [
		{
			eid: "1-s2.0-S073510971838985X-hl0000321",
			itemtitle: "Table of Definitions",
			itemtitleFormatted: "<span>Table of Definitions</span>",
			summary:
				"Table 3 Table of Definitions Term Definition or Description Sinus node dysfunction (with accompanying symptoms) ▪ Sinus bradycardia: Sinus rate &lt;50 bpm ▪ Ectopic atrial bradycardia: Atrial depolarization attributable to an atrial pacemaker othe...",
			contenttype: ["PG", "JL"],
			pubdate: null,
			sectiontitle: [
				"JACC (Journal of the American College of Cardiology)",
				"2018 ACC/AHA/HRS Guideline on the Evaluation and Management of Patients With Bradycardia and Cardiac Conduction Delay",
				"Table of Definitions",
			],
			doi: "10.1016/j.jacc.2018.10.044",
			subtype: "table",
			sectionid: ["hl0000321"],
			sectiontitleformatted: [
				"<span>JACC (Journal of the American College of Cardiology)</span>",
				"<span>2018 ACC/AHA/HRS Guideline on the Evaluation and Management of Patients With Bradycardia and Cardiac Conduction Delay</span>",
				"<span>Table of Definitions</span>",
			],
			refimage: null,
			caption: null,
			loe: null,
			cor: null,
			abs: [],
			comments: [],
			pointofcare: null,
			conditions: null,
			refinfo: null,
			vol: null,
			issue: null,
			pages: null,
			coverdatetext: null,
			coverdatestart: null,
			statustype: "S100",
			citation:
				"J Am Coll Cardiol. 0001 Jan 1. doi: 10.1016/j.jacc.2018.10.044",
			hub: "/Guidelines/Hubs/Bradycardia-and-Cardiac-Conduction-Delay",
			jacclink: "http://www.onlinejacc.org/content/74/7/e51",
			pdflink: "http://www.onlinejacc.org/content/74/7/e51.full.pdf",
			gltitle: "Bradycardia and Cardiac Conduction Delay",
			url: "",
		},
		{
			eid: "1-s2.0-S0735109717413064-hl0001931",
			itemtitle: null,
			itemtitleFormatted: "<span></span>",
			summary:
				"Reviewer Representation Employment Consultant Speakers Bureau Ownership/Partnership/Principal Personal Research Institutional, Organizational, or Other Financial Benefit Salary Expert Witness Alfred E. Buxton Content Reviewer Professor of Medicine...",
			contenttype: ["PG", "JL"],
			pubdate: "1538438400000",
			sectiontitle: [
				"JACC (Journal of the American College of Cardiology)",
				"2017 AHA/ACC/HRS Guideline for Management of Patients With Ventricular Arrhythmias and the Prevention of Sudden Cardiac Death",
			],
			doi: "10.1016/j.jacc.2017.10.054",
			subtype: "table",
			sectionid: ["hl0001931"],
			sectiontitleformatted: [
				"<span>JACC (Journal of the American College of Cardiology)</span>",
				"<span>2017 AHA/ACC/HRS Guideline for Management of Patients With Ventricular Arrhythmias and the Prevention of Sudden Cardiac Death</span>",
			],
			refimage: null,
			caption: null,
			loe: null,
			cor: null,
			abs: [],
			comments: [],
			pointofcare: null,
			conditions: null,
			refinfo: null,
			vol: "72",
			issue: "14",
			pages: "e91-e220",
			coverdatetext: "02 October 2018",
			coverdatestart: "2018-10-02",
			statustype: "S300",
			citation: "J Am Coll Cardiol. 2018 Oct 2;72(14):e91-e220",
			hub: "/Guidelines/Hubs/Ventricular-Arrhythmias",
			jacclink: "http://www.onlinejacc.org/content/72/14/e91",
			pdflink: "http://www.onlinejacc.org/content/72/14/e91.full.pdf",
			gltitle:
				"Ventricular Arrhythmias and the Prevention of Sudden Cardiac Death",
			url: "",
		},
		{
			eid: "1-s2.0-S0735109715058404-hl0000311",
			itemtitle: "Relevant Terms and Definitions",
			itemtitleFormatted: "<span>Relevant Terms and Definitions</span>",
			summary:
				"Table 3 Relevant Terms and Definitions Arrhythmia/Term Definition Supraventricular tachycardia (SVT) An umbrella term used to describe tachycardias (atrial and/or ventricular rates in excess of 100 bpm at rest), the mechanism of which involves tis...",
			contenttype: ["PG", "JL"],
			pubdate: "1459814400000",
			sectiontitle: [
				"JACC (Journal of the American College of Cardiology)",
				"2015 ACC/AHA/HRS Guideline for the Management of Adult Patients With Supraventricular Tachycardia",
				"Relevant Terms and Definitions",
			],
			doi: "10.1016/j.jacc.2015.08.856",
			subtype: "table",
			sectionid: ["hl0000311"],
			sectiontitleformatted: [
				"<span>JACC (Journal of the American College of Cardiology)</span>",
				"<span>2015 ACC/AHA/HRS Guideline for the Management of Adult Patients With Supraventricular Tachycardia</span>",
				"<span>Relevant Terms and Definitions</span>",
			],
			refimage: null,
			caption: null,
			loe: null,
			cor: null,
			abs: [],
			comments: [],
			pointofcare: null,
			conditions: null,
			refinfo: null,
			vol: "67",
			issue: "13",
			pages: "e27-e115",
			coverdatetext: "05 April 2016",
			coverdatestart: "2016-04-05",
			statustype: "S300",
			citation: "J Am Coll Cardiol. 2016 Apr 5;67(13):e27-e115",
			hub: "/Guidelines/Hubs/Supraventricular-Tachycardia",
			jacclink: "http://www.onlinejacc.org/content/67/13/e27",
			pdflink: "http://www.onlinejacc.org/content/67/13/e27.full.pdf",
			gltitle: "Supraventricular Tachycardia",
			url: "",
		},
		{
			eid: "1-s2.0-S0735109717370870-hl0000684",
			itemtitle: "Recommendations for Stage C HF pEF",
			itemtitleFormatted:
				"<span>Recommendations for Stage C HF <i>p</i>EF</span>",
			summary:
				"Recommendations for Stage C HF pEF COR LOE Recommendations Comment/Rationale I B Systolic and diastolic blood pressure should be controlled in patients with HF pEF in accordance with published clinical practice guidelines to prevent morbidity (164...",
			contenttype: ["PG", "JL"],
			pubdate: "1502150400000",
			sectiontitle: [
				"JACC (Journal of the American College of Cardiology)",
				"2017 ACC/AHA/HFSA Focused Update of the 2013 ACCF/AHA Guideline for the Management of Heart Failure",
				"Recommendations for Stage C HF pEF",
			],
			doi: "10.1016/j.jacc.2017.04.025",
			subtype: "table",
			sectionid: ["hl0000684"],
			sectiontitleformatted: [
				"<span>JACC (Journal of the American College of Cardiology)</span>",
				"<span>2017 ACC/AHA/HFSA Focused Update of the 2013 ACCF/AHA Guideline for the Management of Heart Failure</span>",
				"<span>Recommendations for Stage C HF <i>p</i>EF</span>",
			],
			refimage: null,
			caption: null,
			loe: null,
			cor: null,
			abs: [],
			comments: [],
			pointofcare: null,
			conditions: null,
			refinfo: null,
			vol: "70",
			issue: "6",
			pages: "776-803",
			coverdatetext: "08 August 2017",
			coverdatestart: "2017-08-08",
			statustype: "S300",
			citation: "J Am Coll Cardiol. 2017 Aug 8;70(6):776-803",
			hub: "/Guidelines/Hubs/Heart-Failure",
			jacclink: "http://www.onlinejacc.org/content/70/6/776",
			pdflink: "http://www.onlinejacc.org/content/accj/70/6/776.full.pdf",
			gltitle: "Heart Failure (Focused Update)",
			url: "",
		},
		{
			eid: "1-s2.0-S0735109715058404-hl0000593",
			itemtitle: "Acute Drug Therapy for SVT, Intravenous Administration",
			itemtitleFormatted:
				"<span>Acute Drug Therapy for SVT, Intravenous Administration</span>",
			summary:
				"Table 6 Acute Drug Therapy for SVT, Intravenous Administration ∗ Drug Initial Dose Subsequent or Maintenance Dose Potential Adverse Effects Precautions (Exclude or Use With Caution) and Interactions Nucleoside Adenosine 6-mg rapid IV bolus (inject...",
			contenttype: ["PG", "JL"],
			pubdate: "1459814400000",
			sectiontitle: [
				"JACC (Journal of the American College of Cardiology)",
				"2015 ACC/AHA/HRS Guideline for the Management of Adult Patients With Supraventricular Tachycardia",
				"Acute Drug Therapy for SVT, Intravenous Administration",
			],
			doi: "10.1016/j.jacc.2015.08.856",
			subtype: "table",
			sectionid: ["hl0000593"],
			sectiontitleformatted: [
				"<span>JACC (Journal of the American College of Cardiology)</span>",
				"<span>2015 ACC/AHA/HRS Guideline for the Management of Adult Patients With Supraventricular Tachycardia</span>",
				"<span>Acute Drug Therapy for SVT, Intravenous Administration</span>",
			],
			refimage: null,
			caption: null,
			loe: null,
			cor: null,
			abs: [],
			comments: [],
			pointofcare: null,
			conditions: null,
			refinfo: null,
			vol: "67",
			issue: "13",
			pages: "e27-e115",
			coverdatetext: "05 April 2016",
			coverdatestart: "2016-04-05",
			statustype: "S300",
			citation: "J Am Coll Cardiol. 2016 Apr 5;67(13):e27-e115",
			hub: "/Guidelines/Hubs/Supraventricular-Tachycardia",
			jacclink: "http://www.onlinejacc.org/content/67/13/e27",
			pdflink: "http://www.onlinejacc.org/content/67/13/e27.full.pdf",
			gltitle: "Supraventricular Tachycardia",
			url: "",
		},
		{
			eid: "1-s2.0-S0735109720364135-hl0000767",
			itemtitle: null,
			itemtitleFormatted: "<span></span>",
			summary:
				"Committee Member Employment Consultant Speakers Bureau Ownership/ Partnership/ Principal Personal Research Institutional, Organizational, or Other Financial Benefit Expert Witness Voting Recusals by Section ∗ Steve R. Ommen (Chair) Mayo Clinic—Pro...",
			contenttype: ["PG", "JL"],
			pubdate: null,
			sectiontitle: [
				"JACC (Journal of the American College of Cardiology)",
				"2020 AHA/ACC Guideline for the Diagnosis and Treatment of Patients With Hypertrophic Cardiomyopathy",
			],
			doi: "10.1016/j.jacc.2020.08.045",
			subtype: "table",
			sectionid: ["hl0000767"],
			sectiontitleformatted: [
				"<span>JACC (Journal of the American College of Cardiology)</span>",
				"<span>2020 AHA/ACC Guideline for the Diagnosis and Treatment of Patients With Hypertrophic Cardiomyopathy</span>",
			],
			refimage: null,
			caption: null,
			loe: null,
			cor: null,
			abs: [],
			comments: [],
			pointofcare: null,
			conditions: null,
			refinfo: null,
			vol: null,
			issue: null,
			pages: null,
			coverdatetext: null,
			coverdatestart: null,
			statustype: "S200",
			citation:
				"J Am Coll Cardiol. 0001 Jan 1. doi: 10.1016/j.jacc.2020.08.045",
			hub: "/Guidelines/Hubs/Hypertrophic-Cardiomyopathy",
			jacclink: "https://www.jacc.org/doi/10.1016/j.jacc.2020.08.045",
			pdflink: "https://www.jacc.org/doi/pdf/10.1016/j.jacc.2020.08.045",
			gltitle: "Hypertrophic Cardiomyopathy",
			url: "",
		},
		{
			eid: "1-s2.0-S0735109715058404-hl0000895",
			itemtitle: "Ongoing Drug Therapy for SVT, Oral Administration",
			itemtitleFormatted:
				"<span>Ongoing Drug Therapy for SVT, Oral Administration</span>",
			summary:
				"Table 7 Ongoing Drug Therapy for SVT, Oral Administration ∗ Drug Initial Daily Dose(s) Maximum Total Daily Maintenance Dose Potential Adverse Effects Precautions (Exclude or Use With Caution) and Interactions Beta blockers Atenolol 25–50 mg QD 100...",
			contenttype: ["PG", "JL"],
			pubdate: "1459814400000",
			sectiontitle: [
				"JACC (Journal of the American College of Cardiology)",
				"2015 ACC/AHA/HRS Guideline for the Management of Adult Patients With Supraventricular Tachycardia",
				"Ongoing Drug Therapy for SVT, Oral Administration",
			],
			doi: "10.1016/j.jacc.2015.08.856",
			subtype: "table",
			sectionid: ["hl0000895"],
			sectiontitleformatted: [
				"<span>JACC (Journal of the American College of Cardiology)</span>",
				"<span>2015 ACC/AHA/HRS Guideline for the Management of Adult Patients With Supraventricular Tachycardia</span>",
				"<span>Ongoing Drug Therapy for SVT, Oral Administration</span>",
			],
			refimage: null,
			caption: null,
			loe: null,
			cor: null,
			abs: [],
			comments: [],
			pointofcare: null,
			conditions: null,
			refinfo: null,
			vol: "67",
			issue: "13",
			pages: "e27-e115",
			coverdatetext: "05 April 2016",
			coverdatestart: "2016-04-05",
			statustype: "S300",
			citation: "J Am Coll Cardiol. 2016 Apr 5;67(13):e27-e115",
			hub: "/Guidelines/Hubs/Supraventricular-Tachycardia",
			jacclink: "http://www.onlinejacc.org/content/67/13/e27",
			pdflink: "http://www.onlinejacc.org/content/67/13/e27.full.pdf",
			gltitle: "Supraventricular Tachycardia",
			url: "",
		},
		{
			eid: "1-s2.0-S0735109720364135-hl0000641",
			itemtitle:
				"Established Clinical Risk Factors for HCM Sudden Death Risk Stratification",
			itemtitleFormatted:
				"<span>Established Clinical Risk Factors for HCM Sudden Death Risk Stratification</span>",
			summary:
				"Table 7 Established Clinical Risk Factors for HCM Sudden Death Risk Stratification Family history of sudden death from HCM Sudden death judged definitively or likely attributable to HCM in ≥1 first-degree or close relatives who are ≤50 years of ag...",
			contenttype: ["PG", "JL"],
			pubdate: null,
			sectiontitle: [
				"JACC (Journal of the American College of Cardiology)",
				"2020 AHA/ACC Guideline for the Diagnosis and Treatment of Patients With Hypertrophic Cardiomyopathy",
				"Established Clinical Risk Factors for HCM Sudden Death Risk Stratification",
			],
			doi: "10.1016/j.jacc.2020.08.045",
			subtype: "table",
			sectionid: ["hl0000641"],
			sectiontitleformatted: [
				"<span>JACC (Journal of the American College of Cardiology)</span>",
				"<span>2020 AHA/ACC Guideline for the Diagnosis and Treatment of Patients With Hypertrophic Cardiomyopathy</span>",
				"<span>Established Clinical Risk Factors for HCM Sudden Death Risk Stratification</span>",
			],
			refimage: null,
			caption: null,
			loe: null,
			cor: null,
			abs: [],
			comments: [],
			pointofcare: null,
			conditions: null,
			refinfo: null,
			vol: null,
			issue: null,
			pages: null,
			coverdatetext: null,
			coverdatestart: null,
			statustype: "S200",
			citation:
				"J Am Coll Cardiol. 0001 Jan 1. doi: 10.1016/j.jacc.2020.08.045",
			hub: "/Guidelines/Hubs/Hypertrophic-Cardiomyopathy",
			jacclink: "https://www.jacc.org/doi/10.1016/j.jacc.2020.08.045",
			pdflink: "https://www.jacc.org/doi/pdf/10.1016/j.jacc.2020.08.045",
			gltitle: "Hypertrophic Cardiomyopathy",
			url: "",
		},
		{
			eid: "1-s2.0-S0735109720364135-hl0001147",
			itemtitle: null,
			itemtitleFormatted: "<span></span>",
			summary:
				"Reviewer Representation Employment Consultant Speakers Bureau Ownership/ Partnership/ Principal Personal Research Institutional, Organizational, or Other Financial Benefit Expert Witness Anastasia L. Armbruster Joint Committee on Clinical Practice...",
			contenttype: ["PG", "JL"],
			pubdate: null,
			sectiontitle: [
				"JACC (Journal of the American College of Cardiology)",
				"2020 AHA/ACC Guideline for the Diagnosis and Treatment of Patients With Hypertrophic Cardiomyopathy",
			],
			doi: "10.1016/j.jacc.2020.08.045",
			subtype: "table",
			sectionid: ["hl0001147"],
			sectiontitleformatted: [
				"<span>JACC (Journal of the American College of Cardiology)</span>",
				"<span>2020 AHA/ACC Guideline for the Diagnosis and Treatment of Patients With Hypertrophic Cardiomyopathy</span>",
			],
			refimage: null,
			caption: null,
			loe: null,
			cor: null,
			abs: [],
			comments: [],
			pointofcare: null,
			conditions: null,
			refinfo: null,
			vol: null,
			issue: null,
			pages: null,
			coverdatetext: null,
			coverdatestart: null,
			statustype: "S200",
			citation:
				"J Am Coll Cardiol. 0001 Jan 1. doi: 10.1016/j.jacc.2020.08.045",
			hub: "/Guidelines/Hubs/Hypertrophic-Cardiomyopathy",
			jacclink: "https://www.jacc.org/doi/10.1016/j.jacc.2020.08.045",
			pdflink: "https://www.jacc.org/doi/pdf/10.1016/j.jacc.2020.08.045",
			gltitle: "Hypertrophic Cardiomyopathy",
			url: "",
		},
		{
			eid: "1-s2.0-S0735109717415191-hl0000902",
			itemtitle:
				"Causes of Secondary Hypertension With Clinical Indications and Diagnostic Screening Tests",
			itemtitleFormatted:
				"<span>Causes of Secondary Hypertension With Clinical Indications and Diagnostic Screening Tests</span>",
			summary:
				"Table 13 Causes of Secondary Hypertension With Clinical Indications and Diagnostic Screening Tests Prevalence Clinical Indications Physical Examination Screening Tests Additional/Confirmatory Tests Common causes Renal parenchymal disease (S5.4-1,S...",
			contenttype: ["PG", "JL"],
			pubdate: "1526342400000",
			sectiontitle: [
				"JACC (Journal of the American College of Cardiology)",
				"2017 ACC/AHA/AAPA/ABC/ACPM/AGS/APhA/ASH/ASPC/NMA/PCNA Guideline for the Prevention, Detection, Evaluation, and Management of High Blood Pressure in Adults",
				"Causes of Secondary Hypertension With Clinical Indications and Diagnostic Screening Tests",
			],
			doi: "10.1016/j.jacc.2017.11.006",
			subtype: "table",
			sectionid: ["hl0000902"],
			sectiontitleformatted: [
				"<span>JACC (Journal of the American College of Cardiology)</span>",
				"<span>2017 ACC/AHA/AAPA/ABC/ACPM/AGS/APhA/ASH/ASPC/NMA/PCNA Guideline for the Prevention, Detection, Evaluation, and Management of High Blood Pressure in Adults</span>",
				"<span>Causes of Secondary Hypertension With Clinical Indications and Diagnostic Screening Tests</span>",
			],
			refimage: null,
			caption: null,
			loe: null,
			cor: null,
			abs: [],
			comments: [],
			pointofcare: null,
			conditions: null,
			refinfo: null,
			vol: "71",
			issue: "19",
			pages: "e127-e248",
			coverdatetext: "15 May 2018",
			coverdatestart: "2018-05-15",
			statustype: "S300",
			citation: "J Am Coll Cardiol. 2018 May 15;71(19):e127-e248",
			hub: "/Guidelines/Hubs/High-Blood-Pressure",
			jacclink: "http://www.onlinejacc.org/content/71/19/e127",
			pdflink: "http://www.onlinejacc.org/content/71/19/e127.full.pdf",
			gltitle: "High Blood Pressure in Adults",
			url: "",
		},
	],
	facets: {
		"Content Type": [
			{ name: "Articles", count: 82, facetquery: "+contenttype:JL" },
			{
				name: "Practice Guidelines",
				count: 79,
				facetquery: "+contenttype:PG",
			},
		],
		"Point of Care": [],
		Conditions: [],
		"Class of Recommendation": [],
		"Level of Evidence": [],
		Subtype: [{ name: "table", count: 82, facetquery: "+subtype:table" }],
	},
	relations: [],
	didYouMean: [],
	raw: {
		responseHeader: {
			status: 0,
			QTime: 10,
			params: {
				q: "afib",
				product: "acc",
				"acc-filters": "table",
				fl:
					"eid,itemtitle,summary_s,contenttype,pubdate,sectiontitle,doi,subtype,sectionid,refimage,refscp,loe,cor,abs,comments,pointofcare,conditions,refinfo,coverdatetext,vol,issue,pg,coverdatestart,statustype,sectiontitleformatted,itemtitleformatted",
				start: "20",
				rows: "10",
				wt: "json",
			},
		},
		"results-analysis": {
			"facet-properties": {
				"Content Type": "Multi-Select",
				Time: "Single-Select",
				Specialties: "Multi-Select",
				Medline: "Multi-Select",
			},
			sourcelanguage: "eng",
			"searcher-counts": { concept: 82 },
			refinements: {
				query: { imuid: "2790921", concept: "afib" },
				relationship: "autocomplete",
				relations: [],
			},
		},
		"analysis-logging": {
			"Match-Type": "Full-Unique",
			"Concept[0]": {
				IMUID: "2790921",
				Class: "diseases",
				"Med-Name": "atrial fibrillation",
			},
			"Concepts-Found": 1,
		},
		response: {
			numFound: 82,
			start: 20,
			maxScore: 0.0,
			docs: [
				{
					summary_s:
						"Table 3 Table of Definitions Term Definition or Description Sinus node dysfunction (with accompanying symptoms) ▪ Sinus bradycardia: Sinus rate &lt;50 bpm ▪ Ectopic atrial bradycardia: Atrial depolarization attributable to an atrial pacemaker othe...",
					eid: "1-s2.0-S073510971838985X-hl0000321",
					itemtitle: "Table of Definitions",
					itemtitleformatted: "Table of Definitions",
					statustype: "S100",
					doi: "10.1016/j.jacc.2018.10.044",
					sectionid: ["hl0000321"],
					sectiontitleformatted: [
						"JACC (Journal of the American College of Cardiology)",
						"2018 ACC/AHA/HRS Guideline on the Evaluation and Management of Patients With Bradycardia and Cardiac Conduction Delay",
						"Table of Definitions",
					],
					sectiontitle: [
						"JACC (Journal of the American College of Cardiology)",
						"2018 ACC/AHA/HRS Guideline on the Evaluation and Management of Patients With Bradycardia and Cardiac Conduction Delay",
						"Table of Definitions",
					],
					subtype: "table",
					contenttype: ["PG", "JL"],
					_st_: "concept",
				},
				{
					summary_s:
						"Reviewer Representation Employment Consultant Speakers Bureau Ownership/Partnership/Principal Personal Research Institutional, Organizational, or Other Financial Benefit Salary Expert Witness Alfred E. Buxton Content Reviewer Professor of Medicine...",
					eid: "1-s2.0-S0735109717413064-hl0001931",
					vol: "72",
					coverdatetext: "02 October 2018",
					statustype: "S300",
					issue: "14",
					coverdatestart: "2018-10-02",
					doi: "10.1016/j.jacc.2017.10.054",
					sectionid: ["hl0001931"],
					sectiontitleformatted: [
						"JACC (Journal of the American College of Cardiology)",
						"2017 AHA/ACC/HRS Guideline for Management of Patients With Ventricular Arrhythmias and the Prevention of Sudden Cardiac Death",
					],
					sectiontitle: [
						"JACC (Journal of the American College of Cardiology)",
						"2017 AHA/ACC/HRS Guideline for Management of Patients With Ventricular Arrhythmias and the Prevention of Sudden Cardiac Death",
					],
					subtype: "table",
					pubdate: "1538438400000",
					contenttype: ["PG", "JL"],
					pg: "e91-e220",
					_st_: "concept",
				},
				{
					summary_s:
						"Table 3 Relevant Terms and Definitions Arrhythmia/Term Definition Supraventricular tachycardia (SVT) An umbrella term used to describe tachycardias (atrial and/or ventricular rates in excess of 100 bpm at rest), the mechanism of which involves tis...",
					eid: "1-s2.0-S0735109715058404-hl0000311",
					itemtitle: "Relevant Terms and Definitions",
					vol: "67",
					coverdatetext: "05 April 2016",
					statustype: "S300",
					issue: "13",
					coverdatestart: "2016-04-05",
					doi: "10.1016/j.jacc.2015.08.856",
					sectionid: ["hl0000311"],
					sectiontitle: [
						"JACC (Journal of the American College of Cardiology)",
						"2015 ACC/AHA/HRS Guideline for the Management of Adult Patients With Supraventricular Tachycardia",
						"Relevant Terms and Definitions",
					],
					subtype: "table",
					pubdate: "1459814400000",
					contenttype: ["PG", "JL"],
					pg: "e27-e115",
					_st_: "concept",
				},
				{
					summary_s:
						"Recommendations for Stage C HF pEF COR LOE Recommendations Comment/Rationale I B Systolic and diastolic blood pressure should be controlled in patients with HF pEF in accordance with published clinical practice guidelines to prevent morbidity (164...",
					eid: "1-s2.0-S0735109717370870-hl0000684",
					itemtitle: "Recommendations for Stage C HF pEF",
					itemtitleformatted:
						"Recommendations for Stage C HF <ce:italic>p</ce:italic>EF",
					vol: "70",
					coverdatetext: "08 August 2017",
					statustype: "S300",
					issue: "6",
					coverdatestart: "2017-08-08",
					doi: "10.1016/j.jacc.2017.04.025",
					sectionid: ["hl0000684"],
					sectiontitleformatted: [
						"JACC (Journal of the American College of Cardiology)",
						"2017 ACC/AHA/HFSA Focused Update of the 2013 ACCF/AHA Guideline for the Management of Heart Failure",
						"Recommendations for Stage C HF <ce:italic>p</ce:italic>EF",
					],
					sectiontitle: [
						"JACC (Journal of the American College of Cardiology)",
						"2017 ACC/AHA/HFSA Focused Update of the 2013 ACCF/AHA Guideline for the Management of Heart Failure",
						"Recommendations for Stage C HF pEF",
					],
					subtype: "table",
					pubdate: "1502150400000",
					contenttype: ["PG", "JL"],
					pg: "776-803",
					_st_: "concept",
				},
				{
					summary_s:
						"Table 6 Acute Drug Therapy for SVT, Intravenous Administration ∗ Drug Initial Dose Subsequent or Maintenance Dose Potential Adverse Effects Precautions (Exclude or Use With Caution) and Interactions Nucleoside Adenosine 6-mg rapid IV bolus (inject...",
					eid: "1-s2.0-S0735109715058404-hl0000593",
					itemtitle:
						"Acute Drug Therapy for SVT, Intravenous Administration",
					vol: "67",
					coverdatetext: "05 April 2016",
					statustype: "S300",
					issue: "13",
					coverdatestart: "2016-04-05",
					doi: "10.1016/j.jacc.2015.08.856",
					sectionid: ["hl0000593"],
					sectiontitle: [
						"JACC (Journal of the American College of Cardiology)",
						"2015 ACC/AHA/HRS Guideline for the Management of Adult Patients With Supraventricular Tachycardia",
						"Acute Drug Therapy for SVT, Intravenous Administration",
					],
					subtype: "table",
					pubdate: "1459814400000",
					contenttype: ["PG", "JL"],
					pg: "e27-e115",
					_st_: "concept",
				},
				{
					summary_s:
						"Committee Member Employment Consultant Speakers Bureau Ownership/ Partnership/ Principal Personal Research Institutional, Organizational, or Other Financial Benefit Expert Witness Voting Recusals by Section ∗ Steve R. Ommen (Chair) Mayo Clinic—Pro...",
					eid: "1-s2.0-S0735109720364135-hl0000767",
					statustype: "S200",
					doi: "10.1016/j.jacc.2020.08.045",
					sectionid: ["hl0000767"],
					sectiontitleformatted: [
						"JACC (Journal of the American College of Cardiology)",
						"2020 AHA/ACC Guideline for the Diagnosis and Treatment of Patients With Hypertrophic Cardiomyopathy",
					],
					sectiontitle: [
						"JACC (Journal of the American College of Cardiology)",
						"2020 AHA/ACC Guideline for the Diagnosis and Treatment of Patients With Hypertrophic Cardiomyopathy",
					],
					subtype: "table",
					contenttype: ["PG", "JL"],
					_st_: "concept",
				},
				{
					summary_s:
						"Table 7 Ongoing Drug Therapy for SVT, Oral Administration ∗ Drug Initial Daily Dose(s) Maximum Total Daily Maintenance Dose Potential Adverse Effects Precautions (Exclude or Use With Caution) and Interactions Beta blockers Atenolol 25–50 mg QD 100...",
					eid: "1-s2.0-S0735109715058404-hl0000895",
					itemtitle:
						"Ongoing Drug Therapy for SVT, Oral Administration",
					vol: "67",
					coverdatetext: "05 April 2016",
					statustype: "S300",
					issue: "13",
					coverdatestart: "2016-04-05",
					doi: "10.1016/j.jacc.2015.08.856",
					sectionid: ["hl0000895"],
					sectiontitle: [
						"JACC (Journal of the American College of Cardiology)",
						"2015 ACC/AHA/HRS Guideline for the Management of Adult Patients With Supraventricular Tachycardia",
						"Ongoing Drug Therapy for SVT, Oral Administration",
					],
					subtype: "table",
					pubdate: "1459814400000",
					contenttype: ["PG", "JL"],
					pg: "e27-e115",
					_st_: "concept",
				},
				{
					summary_s:
						"Table 7 Established Clinical Risk Factors for HCM Sudden Death Risk Stratification Family history of sudden death from HCM Sudden death judged definitively or likely attributable to HCM in ≥1 first-degree or close relatives who are ≤50 years of ag...",
					eid: "1-s2.0-S0735109720364135-hl0000641",
					itemtitle:
						"Established Clinical Risk Factors for HCM Sudden Death Risk Stratification",
					itemtitleformatted:
						"Established Clinical Risk Factors for HCM Sudden Death Risk Stratification",
					statustype: "S200",
					doi: "10.1016/j.jacc.2020.08.045",
					sectionid: ["hl0000641"],
					sectiontitleformatted: [
						"JACC (Journal of the American College of Cardiology)",
						"2020 AHA/ACC Guideline for the Diagnosis and Treatment of Patients With Hypertrophic Cardiomyopathy",
						"Established Clinical Risk Factors for HCM Sudden Death Risk Stratification",
					],
					sectiontitle: [
						"JACC (Journal of the American College of Cardiology)",
						"2020 AHA/ACC Guideline for the Diagnosis and Treatment of Patients With Hypertrophic Cardiomyopathy",
						"Established Clinical Risk Factors for HCM Sudden Death Risk Stratification",
					],
					subtype: "table",
					contenttype: ["PG", "JL"],
					_st_: "concept",
				},
				{
					summary_s:
						"Reviewer Representation Employment Consultant Speakers Bureau Ownership/ Partnership/ Principal Personal Research Institutional, Organizational, or Other Financial Benefit Expert Witness Anastasia L. Armbruster Joint Committee on Clinical Practice...",
					eid: "1-s2.0-S0735109720364135-hl0001147",
					statustype: "S200",
					doi: "10.1016/j.jacc.2020.08.045",
					sectionid: ["hl0001147"],
					sectiontitleformatted: [
						"JACC (Journal of the American College of Cardiology)",
						"2020 AHA/ACC Guideline for the Diagnosis and Treatment of Patients With Hypertrophic Cardiomyopathy",
					],
					sectiontitle: [
						"JACC (Journal of the American College of Cardiology)",
						"2020 AHA/ACC Guideline for the Diagnosis and Treatment of Patients With Hypertrophic Cardiomyopathy",
					],
					subtype: "table",
					contenttype: ["PG", "JL"],
					_st_: "concept",
				},
				{
					summary_s:
						"Table 13 Causes of Secondary Hypertension With Clinical Indications and Diagnostic Screening Tests Prevalence Clinical Indications Physical Examination Screening Tests Additional/Confirmatory Tests Common causes Renal parenchymal disease (S5.4-1,S...",
					eid: "1-s2.0-S0735109717415191-hl0000902",
					itemtitle:
						"Causes of Secondary Hypertension With Clinical Indications and Diagnostic Screening Tests",
					itemtitleformatted:
						"Causes of Secondary Hypertension With Clinical Indications and Diagnostic Screening Tests",
					vol: "71",
					coverdatetext: "15 May 2018",
					statustype: "S300",
					issue: "19",
					coverdatestart: "2018-05-15",
					doi: "10.1016/j.jacc.2017.11.006",
					sectionid: ["hl0000902"],
					sectiontitleformatted: [
						"JACC (Journal of the American College of Cardiology)",
						"2017 ACC/AHA/AAPA/ABC/ACPM/AGS/APhA/ASH/ASPC/NMA/PCNA Guideline for the Prevention, Detection, Evaluation, and Management of High Blood Pressure in Adults",
						"Causes of Secondary Hypertension With Clinical Indications and Diagnostic Screening Tests",
					],
					sectiontitle: [
						"JACC (Journal of the American College of Cardiology)",
						"2017 ACC/AHA/AAPA/ABC/ACPM/AGS/APhA/ASH/ASPC/NMA/PCNA Guideline for the Prevention, Detection, Evaluation, and Management of High Blood Pressure in Adults",
						"Causes of Secondary Hypertension With Clinical Indications and Diagnostic Screening Tests",
					],
					subtype: "table",
					pubdate: "1526342400000",
					contenttype: ["PG", "JL"],
					pg: "e127-e248",
					_st_: "concept",
				},
			],
		},
		"facet-counts": {
			"Content Type": {
				Articles: { of: "+contenttype:JL", count: 82 },
				"Practice Guidelines": { of: "+contenttype:PG", count: 79 },
			},
			"Point of Care": {},
			Conditions: {},
			"Class of Recommendation": {},
			"Level of Evidence": {},
			Subtype: { table: { of: "+subtype:table", count: 82 } },
		},
	},
};
export const returnResult = {
	results:
		'<div id="undtbl55" class="table"><div><table id="hl0001932"><thead><tr><th id="hl0001945" scope="col" class="table-align-"  >Reviewer</th><th id="hl0001946" scope="col" class="table-align-"  >Representation</th><th id="hl0001947" scope="col" class="table-align-"  >Employment</th><th id="hl0001948" scope="col" class="table-align-"  >Consultant</th><th id="hl0001949" scope="col" class="table-align-"  >Speakers Bureau</th><th id="hl0001950" scope="col" class="table-align-"  >Ownership/Partnership/Principal</th><th id="hl0001951" scope="col" class="table-align-"  >Personal Research</th><th id="hl0001952" scope="col" class="table-align-"  >Institutional, Organizational, or Other Financial Benefit</th><th id="hl0001953" scope="col" class="table-align-"  >Salary</th><th id="hl0001954" scope="col" class="table-align-"  >Expert Witness</th></tr></thead><tbody><tr><td id="hl0001957" class="table-align-"  >Alfred E. Buxton</td><td id="hl0001958" class="table-align-"  >Content Reviewer</td><td id="hl0001959" class="table-align-"  >Professor of Medicine—Harvard Medical School—Beth Israel Deaconess Medical Center</td><td id="hl0001960" class="table-align-"  >None</td><td id="hl0001961" class="table-align-"  >None</td><td id="hl0001962" class="table-align-"  >None</td><td id="hl0001963" class="table-align-"  ><ul id="hl0001964"><li id="hl0001965"><span class="list-item-label">▪</span><p id="hl0001967">NHLBI (DSMB) <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li></ul></td><td id="hl0001969" class="table-align-"  ><ul id="hl0001970"><li id="hl0001971"><span class="list-item-label">▪</span><p id="hl0001973">Medtronic <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li><li id="hl0001975"><span class="list-item-label">▪</span><p id="hl0001977">Biosense Webster <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li></ul></td><td id="hl0001979" class="table-align-"  >None</td><td id="hl0001980" class="table-align-"  >None</td></tr><tr><td id="hl0001982" class="table-align-"  >Andrew E. Epstein</td><td id="hl0001983" class="table-align-"  >Content Reviewer</td><td id="hl0001984" class="table-align-"  >Professor of Medicine—Cardiovascular Division University of Pennsylvania—Chief of Cardiology Section—Philadelphia VA Medical Center</td><td id="hl0001985" class="table-align-"  ><ul id="hl0001986"><li id="hl0001987"><span class="list-item-label">▪</span><p id="hl0001989">Zoll <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0001992" class="table-align-"  >None</td><td id="hl0001993" class="table-align-"  >None</td><td id="hl0001994" class="table-align-"  ><ul id="hl0001995"><li id="hl0001996"><span class="list-item-label">▪</span><p id="hl0001998">Biotronik <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002001"><span class="list-item-label">▪</span><p id="hl0002003">Boston Scientific <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002006"><span class="list-item-label">▪</span><p id="hl0002008">Boston Scientific (DSMB) <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002011"><span class="list-item-label">▪</span><p id="hl0002013">Medtronic <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002016"><span class="list-item-label">▪</span><p id="hl0002018">Medtronic (DSMB)</p></li><li id="hl0002019"><span class="list-item-label">▪</span><p id="hl0002021">St Jude Medical/Abbott <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002024"><span class="list-item-label">▪</span><p id="hl0002026">St Jude Medical/Abbott (DSMB) <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002029" class="table-align-"  >None</td><td id="hl0002030" class="table-align-"  >None</td><td id="hl0002031" class="table-align-"  ><ul id="hl0002032"><li id="hl0002033"><span class="list-item-label">▪</span><p id="hl0002035">Defendant, Amiodarone pulmonary toxicity, 2016</p></li><li id="hl0002036"><span class="list-item-label">▪</span><p id="hl0002038">Defendant, Appropriateness of pacemaker implantation, 2016 <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td></tr><tr><td id="hl0002042" class="table-align-"  >Brian Olshansky</td><td id="hl0002043" class="table-align-"  >Content Reviewer</td><td id="hl0002044" class="table-align-"  >Adjunct Professor of Medicine—Des Moines University—Professor Emeritus—University of Iowa</td><td id="hl0002045" class="table-align-"  ><ul id="hl0002046"><li id="hl0002047"><span class="list-item-label">▪</span><p id="hl0002049">Boehringer Ingleheim</p></li><li id="hl0002050"><span class="list-item-label">▪</span><p id="hl0002052">Lundbeck Inc <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002055"><span class="list-item-label">▪</span><p id="hl0002057">On-X/Cryolife</p></li></ul></td><td id="hl0002058" class="table-align-"  ><ul id="hl0002059"><li id="hl0002060"><span class="list-item-label">▪</span><p id="hl0002062">Lundbeck Inc <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002065"><span class="list-item-label">▪</span><p id="hl0002067">On-X/Cryolife</p></li></ul></td><td id="hl0002068" class="table-align-"  >None</td><td id="hl0002069" class="table-align-"  ><ul id="hl0002070"><li id="hl0002071"><span class="list-item-label">▪</span><p id="hl0002073">Amarin (DSMB) <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002076" class="table-align-"  >None</td><td id="hl0002077" class="table-align-"  >None</td><td id="hl0002078" class="table-align-"  ><ul id="hl0002079"><li id="hl0002080"><span class="list-item-label">▪</span><p id="hl0002082">Plaintiff, Long QT sudden death, 2017</p></li></ul></td></tr><tr><td id="hl0002084" class="table-align-"  >Bulent Gorenek</td><td id="hl0002085" class="table-align-"  >Content Reviewer—ACC EP Council</td><td id="hl0002086" class="table-align-"  ></td><td id="hl0002087" class="table-align-"  >None</td><td id="hl0002088" class="table-align-"  >None</td><td id="hl0002089" class="table-align-"  >None</td><td id="hl0002090" class="table-align-"  >None</td><td id="hl0002091" class="table-align-"  >None</td><td id="hl0002092" class="table-align-"  >None</td><td id="hl0002093" class="table-align-"  >None</td></tr><tr><td id="hl0002095" class="table-align-"  >Charles I. Berul</td><td id="hl0002096" class="table-align-"  >Content Reviewer</td><td id="hl0002097" class="table-align-"  >Division Chief of Pediatric Cardiology—Children&#x27;s National Medical Center</td><td id="hl0002098" class="table-align-"  >None</td><td id="hl0002099" class="table-align-"  >None</td><td id="hl0002100" class="table-align-"  >None</td><td id="hl0002101" class="table-align-"  >None</td><td id="hl0002102" class="table-align-"  ><ul id="hl0002103"><li id="hl0002104"><span class="list-item-label">▪</span><p id="hl0002106">Circulation <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002109" class="table-align-"  >None</td><td id="hl0002110" class="table-align-"  >None</td></tr><tr><td id="hl0002112" class="table-align-"  >Darren Sudman</td><td id="hl0002113" class="table-align-"  >Content Reviewer</td><td id="hl0002114" class="table-align-"  >Executive Director—Simon’s Fund</td><td id="hl0002115" class="table-align-"  >None</td><td id="hl0002116" class="table-align-"  >None</td><td id="hl0002117" class="table-align-"  >None</td><td id="hl0002118" class="table-align-"  >None</td><td id="hl0002119" class="table-align-"  >None</td><td id="hl0002120" class="table-align-"  >None</td><td id="hl0002121" class="table-align-"  >None</td></tr><tr><td id="hl0002123" class="table-align-"  >George J. Klein</td><td id="hl0002124" class="table-align-"  >Content Reviewer</td><td id="hl0002125" class="table-align-"  >Chief of Cardiology—London Health Sciences Center</td><td id="hl0002126" class="table-align-"  ><ul id="hl0002127"><li id="hl0002128"><span class="list-item-label">▪</span><p id="hl0002130">Biotronik</p></li><li id="hl0002131"><span class="list-item-label">▪</span><p id="hl0002133">Boston Scientific</p></li><li id="hl0002134"><span class="list-item-label">▪</span><p id="hl0002136">Medtronic <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002139" class="table-align-"  >None</td><td id="hl0002140" class="table-align-"  >None</td><td id="hl0002141" class="table-align-"  >None</td><td id="hl0002142" class="table-align-"  >None</td><td id="hl0002143" class="table-align-"  >None</td><td id="hl0002144" class="table-align-"  >None</td></tr><tr><td id="hl0002146" class="table-align-"  >Glenn N. Levine</td><td id="hl0002147" class="table-align-"  >Content Reviewer—ACC/AHA Task Force on Clinical Practice Guidelines</td><td id="hl0002148" class="table-align-"  >Professor of Medicine—Baylor College of Medicine <br>Director—Cardiac Care Unit—Michael E. DeBakey Medical Center </td><td id="hl0002150" class="table-align-"  >None</td><td id="hl0002151" class="table-align-"  >None</td><td id="hl0002152" class="table-align-"  >None</td><td id="hl0002153" class="table-align-"  >None</td><td id="hl0002154" class="table-align-"  >None</td><td id="hl0002155" class="table-align-"  >None</td><td id="hl0002156" class="table-align-"  ><ul id="hl0002157"><li id="hl0002158"><span class="list-item-label">▪</span><p id="hl0002160">Defendant, Catheterization Laboratory Procedure, 2016</p></li><li id="hl0002161"><span class="list-item-label">▪</span><p id="hl0002163">Defendant, Out of hospital death, 2016</p></li></ul></td></tr><tr><td id="hl0002165" class="table-align-"  >Gurusher S. Panjrath</td><td id="hl0002166" class="table-align-"  >Content Reviewer—ACC Heart Failure and Transplant Council</td><td id="hl0002167" class="table-align-"  >Director Heart Failure and Mechanical Support Program—George Washington University</td><td id="hl0002168" class="table-align-"  ><ul id="hl0002169"><li id="hl0002170"><span class="list-item-label">▪</span><p id="hl0002172">Amgen Inc. <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002175" class="table-align-"  >None</td><td id="hl0002176" class="table-align-"  >None</td><td id="hl0002177" class="table-align-"  >None</td><td id="hl0002178" class="table-align-"  ><ul id="hl0002179"><li id="hl0002180"><span class="list-item-label">▪</span><p id="hl0002182">BEAT-HF <a class="inline-reference" href="#dtbl2fnddagger">‡</a></p></li><li id="hl0002184"><span class="list-item-label">▪</span><p id="hl0002186">ENDEAVOUR <a class="inline-reference" href="#dtbl2fnddagger">‡</a></p></li></ul></td><td id="hl0002188" class="table-align-"  >None</td><td id="hl0002189" class="table-align-"  >None</td></tr><tr><td id="hl0002191" class="table-align-"  >James P. Daubert</td><td id="hl0002192" class="table-align-"  >Official Reviewer—AHA</td><td id="hl0002193" class="table-align-"  >Duke University Medical Center</td><td id="hl0002194" class="table-align-"  ><ul id="hl0002195"><li id="hl0002196"><span class="list-item-label">▪</span><p id="hl0002198">Biosense Webster</p></li><li id="hl0002199"><span class="list-item-label">▪</span><p id="hl0002201">Boston Scientific</p></li><li id="hl0002202"><span class="list-item-label">▪</span><p id="hl0002204">CardioFocus</p></li><li id="hl0002205"><span class="list-item-label">▪</span><p id="hl0002207">Gilead</p></li><li id="hl0002208"><span class="list-item-label">▪</span><p id="hl0002210">Heart Metabolics</p></li><li id="hl0002211"><span class="list-item-label">▪</span><p id="hl0002213">Medtronic <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002216"><span class="list-item-label">▪</span><p id="hl0002218">St. Jude Medical</p></li><li id="hl0002219"><span class="list-item-label">▪</span><p id="hl0002221">Zoll</p></li></ul></td><td id="hl0002222" class="table-align-"  >None</td><td id="hl0002223" class="table-align-"  >None</td><td id="hl0002224" class="table-align-"  ><ul id="hl0002225"><li id="hl0002226"><span class="list-item-label">▪</span><p id="hl0002228">ARCA biopharma</p></li><li id="hl0002229"><span class="list-item-label">▪</span><p id="hl0002231">Biosense Webster <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002234"><span class="list-item-label">▪</span><p id="hl0002236">Boston Scientific <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002239"><span class="list-item-label">▪</span><p id="hl0002241">Gilead <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002244"><span class="list-item-label">▪</span><p id="hl0002246">Gilead (DSMB)</p></li><li id="hl0002247"><span class="list-item-label">▪</span><p id="hl0002249">Medtronic <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002252"><span class="list-item-label">▪</span><p id="hl0002254">NHLBI <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002257"><span class="list-item-label">▪</span><p id="hl0002259">NHLBI (DSMB)</p></li><li id="hl0002260"><span class="list-item-label">▪</span><p id="hl0002262">Northwestern University</p></li><li id="hl0002263"><span class="list-item-label">▪</span><p id="hl0002265">St. Jude Medical (DSMB)</p></li><li id="hl0002266"><span class="list-item-label">▪</span><p id="hl0002268">VytronUS (DSMB)</p></li></ul></td><td id="hl0002269" class="table-align-"  ><ul id="hl0002270"><li id="hl0002271"><span class="list-item-label">▪</span><p id="hl0002273">Biosense <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002276"><span class="list-item-label">▪</span><p id="hl0002278">Biotronik <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002281"><span class="list-item-label">▪</span><p id="hl0002283">Boston Scientific <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002286"><span class="list-item-label">▪</span><p id="hl0002288">Gilead Sciences, Inc. <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002291"><span class="list-item-label">▪</span><p id="hl0002293">Medtronic <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002296"><span class="list-item-label">▪</span><p id="hl0002298">St. Jude Medical <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002301" class="table-align-"  ><ul id="hl0002302"><li id="hl0002303"><span class="list-item-label">▪</span><p id="hl0002305">ACC</p></li></ul></td><td id="hl0002306" class="table-align-"  >None</td></tr><tr><td id="hl0002308" class="table-align-"  >James Tisdale</td><td id="hl0002309" class="table-align-"  >Content Reviewer—ACC EP Council</td><td id="hl0002310" class="table-align-"  >Professor—College of Pharmacy <br>Purdue University—Adjunct Professor—School of Medicine <br>Indiana University </td><td id="hl0002313" class="table-align-"  >None</td><td id="hl0002314" class="table-align-"  >None</td><td id="hl0002315" class="table-align-"  >None</td><td id="hl0002316" class="table-align-"  ><ul id="hl0002317"><li id="hl0002318"><span class="list-item-label">▪</span><p id="hl0002320">AHA <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002323"><span class="list-item-label">▪</span><p id="hl0002325">HRS <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002328"><span class="list-item-label">▪</span><p id="hl0002330">Indiana Clinical Translational Sciences Institute/Strategic Research Initiative <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002333" class="table-align-"  ><ul id="hl0002334"><li id="hl0002335"><span class="list-item-label">▪</span><p id="hl0002337">ACC <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li><li id="hl0002339"><span class="list-item-label">▪</span><p id="hl0002341">AHA <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li><li id="hl0002343"><span class="list-item-label">▪</span><p id="hl0002345">AZCert <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li><li id="hl0002347"><span class="list-item-label">▪</span><p id="hl0002349">QT drugs list, credible meds.org <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li></ul></td><td id="hl0002351" class="table-align-"  >None</td><td id="hl0002352" class="table-align-"  ><ul id="hl0002353"><li id="hl0002354"><span class="list-item-label">▪</span><p id="hl0002356">Plaintiff, Drug-induced torsades de pointes, 2017 <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td></tr><tr><td id="hl0002360" class="table-align-"  >John L. Sapp</td><td id="hl0002361" class="table-align-"  >Official Reviewer—HRS</td><td id="hl0002362" class="table-align-"  >Interim Head—Division of Cardiology <br>QEII Health Sciences Centre—Professor of Medicine—Dalhousie University </td><td id="hl0002364" class="table-align-"  ><ul id="hl0002365"><li id="hl0002366"><span class="list-item-label">▪</span><p id="hl0002368">Biosense Webster <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002371"><span class="list-item-label">▪</span><p id="hl0002373">Medtronic</p></li><li id="hl0002374"><span class="list-item-label">▪</span><p id="hl0002376">St. Jude</p></li></ul></td><td id="hl0002377" class="table-align-"  >None</td><td id="hl0002378" class="table-align-"  >None</td><td id="hl0002379" class="table-align-"  ><ul id="hl0002380"><li id="hl0002381"><span class="list-item-label">▪</span><p id="hl0002383">Biosense Webster <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002386"><span class="list-item-label">▪</span><p id="hl0002388">Canadian Institute of Health Research <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002391"><span class="list-item-label">▪</span><p id="hl0002393">DSMB <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li><li id="hl0002395"><span class="list-item-label">▪</span><p id="hl0002397">Phillips healthcare <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002400"><span class="list-item-label">▪</span><p id="hl0002402">St. Jude Medical <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002405" class="table-align-"  ><ul id="hl0002406"><li id="hl0002407"><span class="list-item-label">▪</span><p id="hl0002409">ARTESiA <a class="inline-reference" href="#dtbl2fnddagger">‡</a></p></li><li id="hl0002411"><span class="list-item-label">▪</span><p id="hl0002413">Medtronic <a class="inline-reference" href="#dtbl2fnddagger">‡</a></p></li><li id="hl0002415"><span class="list-item-label">▪</span><p id="hl0002417">Optisure Registry <a class="inline-reference" href="#dtbl2fnddagger">‡</a></p></li><li id="hl0002419"><span class="list-item-label">▪</span><p id="hl0002421">St. Jude <a class="inline-reference" href="#dtbl2fnddagger">‡</a></p></li></ul></td><td id="hl0002423" class="table-align-"  >None</td><td id="hl0002424" class="table-align-"  >None</td></tr><tr><td id="hl0002426" class="table-align-"  >Joseph Edward Marine</td><td id="hl0002427" class="table-align-"  >Official Reviewer—ACC</td><td id="hl0002428" class="table-align-"  >Associate Professor of Medicine—Johns Hopkins University School of Medicine</td><td id="hl0002429" class="table-align-"  >None</td><td id="hl0002430" class="table-align-"  >None</td><td id="hl0002431" class="table-align-"  >None</td><td id="hl0002432" class="table-align-"  >None</td><td id="hl0002433" class="table-align-"  ><ul id="hl0002434"><li id="hl0002435"><span class="list-item-label">▪</span><p id="hl0002437">UpToDate</p></li></ul></td><td id="hl0002438" class="table-align-"  >None</td><td id="hl0002439" class="table-align-"  >None</td></tr><tr><td id="hl0002441" class="table-align-"  >Kathleen T. Hickey</td><td id="hl0002442" class="table-align-"  >Official Reviewer—AHA</td><td id="hl0002443" class="table-align-"  >Professor of Nursing—Columbia University Medical Center</td><td id="hl0002444" class="table-align-"  >None</td><td id="hl0002445" class="table-align-"  >None</td><td id="hl0002446" class="table-align-"  >None</td><td id="hl0002447" class="table-align-"  >None</td><td id="hl0002448" class="table-align-"  >None</td><td id="hl0002449" class="table-align-"  >None</td><td id="hl0002450" class="table-align-"  >None</td></tr><tr><td id="hl0002452" class="table-align-"  >Kenneth A. Ellenbogen</td><td id="hl0002453" class="table-align-"  >Content Reviewer</td><td id="hl0002454" class="table-align-"  >Chief of Cardiology—Virginia Commonwealth University Medical Center</td><td id="hl0002455" class="table-align-"  ><ul id="hl0002456"><li id="hl0002457"><span class="list-item-label">▪</span><p id="hl0002459">AHA</p></li><li id="hl0002460"><span class="list-item-label">▪</span><p id="hl0002462">AtriCure <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002465"><span class="list-item-label">▪</span><p id="hl0002467">Biosense Webster <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002470"><span class="list-item-label">▪</span><p id="hl0002472">Biotronik <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002475"><span class="list-item-label">▪</span><p id="hl0002477">Boston Science <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002480"><span class="list-item-label">▪</span><p id="hl0002482">Capricor</p></li><li id="hl0002483"><span class="list-item-label">▪</span><p id="hl0002485">HRS</p></li><li id="hl0002486"><span class="list-item-label">▪</span><p id="hl0002488">Janssen</p></li><li id="hl0002489"><span class="list-item-label">▪</span><p id="hl0002491">Medtronic <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002494"><span class="list-item-label">▪</span><p id="hl0002496">Pfizer <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002499"><span class="list-item-label">▪</span><p id="hl0002501">Sentra heart</p></li><li id="hl0002502"><span class="list-item-label">▪</span><p id="hl0002504">St. Jude Medical <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002507" class="table-align-"  >None</td><td id="hl0002508" class="table-align-"  >None</td><td id="hl0002509" class="table-align-"  ><ul id="hl0002510"><li id="hl0002511"><span class="list-item-label">▪</span><p id="hl0002513">AtriCure <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002516"><span class="list-item-label">▪</span><p id="hl0002518">Biosense Webster <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002521"><span class="list-item-label">▪</span><p id="hl0002523">Boston Science <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002526"><span class="list-item-label">▪</span><p id="hl0002528">Daiichi Sankyo</p></li><li id="hl0002529"><span class="list-item-label">▪</span><p id="hl0002531">Medtronic <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002534"><span class="list-item-label">▪</span><p id="hl0002536">Medtronic (DSMB) <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002539"><span class="list-item-label">▪</span><p id="hl0002541">NIH <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002544"><span class="list-item-label">▪</span><p id="hl0002546">Pfizer <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002549" class="table-align-"  ><ul id="hl0002550"><li id="hl0002551"><span class="list-item-label">▪</span><p id="hl0002553">Biosense Webster <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002556"><span class="list-item-label">▪</span><p id="hl0002558">Boston Science <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002561"><span class="list-item-label">▪</span><p id="hl0002563">Circulation <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li><li id="hl0002565"><span class="list-item-label">▪</span><p id="hl0002567">Heart Rhythm <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li><li id="hl0002569"><span class="list-item-label">▪</span><p id="hl0002571">JACC <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li><li id="hl0002573"><span class="list-item-label">▪</span><p id="hl0002575">Medtronic <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002578"><span class="list-item-label">▪</span><p id="hl0002580">PACE <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li><li id="hl0002582"><span class="list-item-label">▪</span><p id="hl0002584">Sanofi Aventis</p></li></ul></td><td id="hl0002585" class="table-align-"  >None</td><td id="hl0002586" class="table-align-"  >None</td></tr><tr><td id="hl0002588" class="table-align-"  >Kim K. Birtcher</td><td id="hl0002589" class="table-align-"  >Content Reviewer—ACC/AHA Task Force on Clinical Practice Guidelines</td><td id="hl0002590" class="table-align-"  >University of Houston—College of Pharmacology</td><td id="hl0002591" class="table-align-"  ><ul id="hl0002592"><li id="hl0002593"><span class="list-item-label">▪</span><p id="hl0002595">Jones and Bartlett Learning</p></li></ul></td><td id="hl0002596" class="table-align-"  >None</td><td id="hl0002597" class="table-align-"  >None</td><td id="hl0002598" class="table-align-"  >None</td><td id="hl0002599" class="table-align-"  ><ul id="hl0002600"><li id="hl0002601"><span class="list-item-label">▪</span><p id="hl0002603">Accreditation Council for Clinical Lipidology</p></li></ul></td><td id="hl0002604" class="table-align-"  ><ul id="hl0002605"><li id="hl0002606"><span class="list-item-label">▪</span><p id="hl0002608">University of Houston College of Pharmacology <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002611"><span class="list-item-label">▪</span><p id="hl0002613">Walgreens <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002616" class="table-align-"  >None</td></tr><tr><td id="hl0002618" class="table-align-"  >Kristen B. Campbell</td><td id="hl0002619" class="table-align-"  >Content Reviewer</td><td id="hl0002620" class="table-align-"  >Duke University Hospital</td><td id="hl0002621" class="table-align-"  >None</td><td id="hl0002622" class="table-align-"  >None</td><td id="hl0002623" class="table-align-"  >None</td><td id="hl0002624" class="table-align-"  >None</td><td id="hl0002625" class="table-align-"  >None</td><td id="hl0002626" class="table-align-"  >None</td><td id="hl0002627" class="table-align-"  >None</td></tr><tr><td id="hl0002629" class="table-align-"  >Kristen K. Patton</td><td id="hl0002630" class="table-align-"  >Content Reviewer</td><td id="hl0002631" class="table-align-"  >Professor of Medicine—University of Washington</td><td id="hl0002632" class="table-align-"  >None</td><td id="hl0002633" class="table-align-"  >None</td><td id="hl0002634" class="table-align-"  >None</td><td id="hl0002635" class="table-align-"  >None</td><td id="hl0002636" class="table-align-"  ><ul id="hl0002637"><li id="hl0002638"><span class="list-item-label">▪</span><p id="hl0002640">ABIM</p></li><li id="hl0002641"><span class="list-item-label">▪</span><p id="hl0002643">ACGME <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li><li id="hl0002645"><span class="list-item-label">▪</span><p id="hl0002647">AHA <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li><li id="hl0002649"><span class="list-item-label">▪</span><p id="hl0002651">FDA</p></li><li id="hl0002652"><span class="list-item-label">▪</span><p id="hl0002654">HRS <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li></ul></td><td id="hl0002656" class="table-align-"  >None</td><td id="hl0002657" class="table-align-"  >None</td></tr><tr><td id="hl0002659" class="table-align-"  >L. Brent Mitchell</td><td id="hl0002660" class="table-align-"  >Content Reviewer</td><td id="hl0002661" class="table-align-"  >Professor—Department of Cardiac Sciences—Libin Cardiovascular Institute of Alberta—University of Calgary—Alberta Health Services</td><td id="hl0002662" class="table-align-"  ><ul id="hl0002663"><li id="hl0002664"><span class="list-item-label">▪</span><p id="hl0002666">Boehringer Ingelheim <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002669"><span class="list-item-label">▪</span><p id="hl0002671">Forest Pharmaceuticals</p></li><li id="hl0002672"><span class="list-item-label">▪</span><p id="hl0002674">Guidant Canada <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002677"><span class="list-item-label">▪</span><p id="hl0002679">Medtronic Canada <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002682"><span class="list-item-label">▪</span><p id="hl0002684">Medtronic Inc <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002687"><span class="list-item-label">▪</span><p id="hl0002689">Merck</p></li><li id="hl0002690"><span class="list-item-label">▪</span><p id="hl0002692">Pfizer <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002695"><span class="list-item-label">▪</span><p id="hl0002697">Servier Canada <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002700" class="table-align-"  >None</td><td id="hl0002701" class="table-align-"  >None</td><td id="hl0002702" class="table-align-"  ><ul id="hl0002703"><li id="hl0002704"><span class="list-item-label">▪</span><p id="hl0002706">Boston Scientific <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002709" class="table-align-"  ><ul id="hl0002710"><li id="hl0002711"><span class="list-item-label">▪</span><p id="hl0002713">ARTESIA <a class="inline-reference" href="#dtbl2fnddagger">‡</a></p></li><li id="hl0002715"><span class="list-item-label">▪</span><p id="hl0002717">Health Protection Branch, Government of Canada</p></li></ul></td><td id="hl0002718" class="table-align-"  >None</td><td id="hl0002719" class="table-align-"  >None</td></tr><tr><td id="hl0002721" class="table-align-"  >Martin Borggrefe</td><td id="hl0002722" class="table-align-"  >Content Reviewer</td><td id="hl0002723" class="table-align-"  >I Medizinische KlinikKlinikum Mannheim <br>GmbHUniversitätsklinikum </td><td id="hl0002725" class="table-align-"  ><ul id="hl0002726"><li id="hl0002727"><span class="list-item-label">▪</span><p id="hl0002729">Bayer Health Care</p></li><li id="hl0002730"><span class="list-item-label">▪</span><p id="hl0002732">Boehringer Ingelheim</p></li><li id="hl0002733"><span class="list-item-label">▪</span><p id="hl0002735">Impulse Dynamics</p></li><li id="hl0002736"><span class="list-item-label">▪</span><p id="hl0002738">Sanofi Aventis</p></li><li id="hl0002739"><span class="list-item-label">▪</span><p id="hl0002741">St. Jude Medical</p></li></ul></td><td id="hl0002742" class="table-align-"  >None</td><td id="hl0002743" class="table-align-"  >None</td><td id="hl0002744" class="table-align-"  ><ul id="hl0002745"><li id="hl0002746"><span class="list-item-label">▪</span><p id="hl0002748">German Centre for Cardiovascular Research <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002751" class="table-align-"  >None</td><td id="hl0002752" class="table-align-"  >None</td><td id="hl0002753" class="table-align-"  >None</td></tr><tr><td id="hl0002755" class="table-align-"  >Mathew D. Hutchinson</td><td id="hl0002756" class="table-align-"  >Official Reviewer—HRS</td><td id="hl0002757" class="table-align-"  >Professor of Medicine—University of Arizona College of Medicine—Tucson</td><td id="hl0002758" class="table-align-"  ><ul id="hl0002759"><li id="hl0002760"><span class="list-item-label">▪</span><p id="hl0002762">St. Jude Medical</p></li></ul></td><td id="hl0002763" class="table-align-"  >None</td><td id="hl0002764" class="table-align-"  >None</td><td id="hl0002765" class="table-align-"  >None</td><td id="hl0002766" class="table-align-"  >None</td><td id="hl0002767" class="table-align-"  >None</td><td id="hl0002768" class="table-align-"  >None</td></tr><tr><td id="hl0002770" class="table-align-"  >Matthew W. Martinez</td><td id="hl0002771" class="table-align-"  >Content Reviewer—Sports and Exercise EP Council</td><td id="hl0002772" class="table-align-"  >Lehigh Valley Health Network</td><td id="hl0002773" class="table-align-"  >None</td><td id="hl0002774" class="table-align-"  >None</td><td id="hl0002775" class="table-align-"  >None</td><td id="hl0002776" class="table-align-"  >None</td><td id="hl0002777" class="table-align-"  >None</td><td id="hl0002778" class="table-align-"  >None</td><td id="hl0002779" class="table-align-"  >None</td></tr><tr><td id="hl0002781" class="table-align-"  >Melissa R. Robinson</td><td id="hl0002782" class="table-align-"  >Content Reviewer</td><td id="hl0002783" class="table-align-"  >Director—Complex Ablation Program—University of Washington</td><td id="hl0002784" class="table-align-"  ><ul id="hl0002785"><li id="hl0002786"><span class="list-item-label">▪</span><p id="hl0002788">Medtronic <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002791"><span class="list-item-label">▪</span><p id="hl0002793">Abbott <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002796"><span class="list-item-label">▪</span><p id="hl0002798">Boston Scientific <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002801" class="table-align-"  >None</td><td id="hl0002802" class="table-align-"  >None</td><td id="hl0002803" class="table-align-"  >None</td><td id="hl0002804" class="table-align-"  >None</td><td id="hl0002805" class="table-align-"  >None</td><td id="hl0002806" class="table-align-"  >None</td></tr><tr><td id="hl0002808" class="table-align-"  >Michael J. Silka</td><td id="hl0002809" class="table-align-"  >Content Reviewer</td><td id="hl0002810" class="table-align-"  >Children&#x27;s Hospital Los Angeles</td><td id="hl0002811" class="table-align-"  >None</td><td id="hl0002812" class="table-align-"  >None</td><td id="hl0002813" class="table-align-"  >None</td><td id="hl0002814" class="table-align-"  >None</td><td id="hl0002815" class="table-align-"  >None</td><td id="hl0002816" class="table-align-"  >None</td><td id="hl0002817" class="table-align-"  ><ul id="hl0002818"><li id="hl0002819"><span class="list-item-label">▪</span><p id="hl0002821">Defendant, ICD implantation, 2017</p></li></ul></td></tr><tr><td id="hl0002823" class="table-align-"  >Miguel A. Quinones</td><td id="hl0002824" class="table-align-"  >Content Reviewer</td><td id="hl0002825" class="table-align-"  >Methodist DeBakey Heart and Vascular Center</td><td id="hl0002826" class="table-align-"  >None</td><td id="hl0002827" class="table-align-"  >None</td><td id="hl0002828" class="table-align-"  >None</td><td id="hl0002829" class="table-align-"  >None</td><td id="hl0002830" class="table-align-"  ><ul id="hl0002831"><li id="hl0002832"><span class="list-item-label">▪</span><p id="hl0002834">Houston Methodist Hospital <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002837" class="table-align-"  >None</td><td id="hl0002838" class="table-align-"  >None</td></tr><tr><td id="hl0002840" class="table-align-"  >Mitchell T. Saltzberg</td><td id="hl0002841" class="table-align-"  >Organizational Reviewer—HFSA</td><td id="hl0002842" class="table-align-"  >Jefferson Medical College—Christiana Care Health System</td><td id="hl0002843" class="table-align-"  >None</td><td id="hl0002844" class="table-align-"  >None</td><td id="hl0002845" class="table-align-"  ><ul id="hl0002846"><li id="hl0002847"><span class="list-item-label">▪</span><p id="hl0002849">Nephroceuticals <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002852"><span class="list-item-label">▪</span><p id="hl0002854">Stem Cell Theranostics <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002857" class="table-align-"  >None</td><td id="hl0002858" class="table-align-"  >None</td><td id="hl0002859" class="table-align-"  >None</td><td id="hl0002860" class="table-align-"  >None</td></tr><tr><td id="hl0002862" class="table-align-"  >N.A. Mark Estes III</td><td id="hl0002863" class="table-align-"  >Content Reviewer</td><td id="hl0002864" class="table-align-"  >Professor of Medicine—Tufts University School of Medicine</td><td id="hl0002865" class="table-align-"  ><ul id="hl0002866"><li id="hl0002867"><span class="list-item-label">▪</span><p id="hl0002869">Boston Scientific <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002872"><span class="list-item-label">▪</span><p id="hl0002874">Medtronic <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002877"><span class="list-item-label">▪</span><p id="hl0002879">St. Jude Medical <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002882" class="table-align-"  >None</td><td id="hl0002883" class="table-align-"  >None</td><td id="hl0002884" class="table-align-"  ><ul id="hl0002885"><li id="hl0002886"><span class="list-item-label">▪</span><p id="hl0002888">Boston Scientific <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002891"><span class="list-item-label">▪</span><p id="hl0002893">International Board of Heart Rhythm Examiners <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li><li id="hl0002895"><span class="list-item-label">▪</span><p id="hl0002897">Medtronic <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002900"><span class="list-item-label">▪</span><p id="hl0002902">St. Jude Medical <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002905" class="table-align-"  >None</td><td id="hl0002906" class="table-align-"  >None</td><td id="hl0002907" class="table-align-"  >None</td></tr><tr><td id="hl0002909" class="table-align-"  >Norma M. Keller</td><td id="hl0002910" class="table-align-"  >Official Reviewer—ACC</td><td id="hl0002911" class="table-align-"  >New York University Medical Center</td><td id="hl0002912" class="table-align-"  >None</td><td id="hl0002913" class="table-align-"  >None</td><td id="hl0002914" class="table-align-"  >None</td><td id="hl0002915" class="table-align-"  >None</td><td id="hl0002916" class="table-align-"  >None</td><td id="hl0002917" class="table-align-"  >None</td><td id="hl0002918" class="table-align-"  >None</td></tr><tr><td id="hl0002920" class="table-align-"  >Peter Leong-Sit</td><td id="hl0002921" class="table-align-"  >Content Reviewer—HRS</td><td id="hl0002922" class="table-align-"  >Associate Professor of Medicine—Western University—London Health Sciences Centre</td><td id="hl0002923" class="table-align-"  ><ul id="hl0002924"><li id="hl0002925"><span class="list-item-label">▪</span><p id="hl0002927">Medtronic Canada</p></li></ul></td><td id="hl0002928" class="table-align-"  ><ul id="hl0002929"><li id="hl0002930"><span class="list-item-label">▪</span><p id="hl0002932">Bayer Healthcare Pharmaceuticals</p></li><li id="hl0002933"><span class="list-item-label">▪</span><p id="hl0002935">Biosense Webster</p></li><li id="hl0002936"><span class="list-item-label">▪</span><p id="hl0002938">Johnson and Johnson</p></li></ul></td><td id="hl0002939" class="table-align-"  >None</td><td id="hl0002940" class="table-align-"  >None</td><td id="hl0002941" class="table-align-"  >None</td><td id="hl0002942" class="table-align-"  ><ul id="hl0002943"><li id="hl0002944"><span class="list-item-label">▪</span><p id="hl0002946">Bayer Healthcare Pharmaceuticals <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002949" class="table-align-"  >None</td></tr><tr><td id="hl0002951" class="table-align-"  >Rachel J. Lampert</td><td id="hl0002952" class="table-align-"  >Content Reviewer</td><td id="hl0002953" class="table-align-"  >Yale University School of Medicine—Section of Cardiology</td><td id="hl0002954" class="table-align-"  ><ul id="hl0002955"><li id="hl0002956"><span class="list-item-label">▪</span><p id="hl0002958">Medtronic <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002961" class="table-align-"  >None</td><td id="hl0002962" class="table-align-"  >None</td><td id="hl0002963" class="table-align-"  ><ul id="hl0002964"><li id="hl0002965"><span class="list-item-label">▪</span><p id="hl0002967">Boston Scientific <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002970"><span class="list-item-label">▪</span><p id="hl0002972">GE Medical <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002975"><span class="list-item-label">▪</span><p id="hl0002977">Medtronic, Inc. <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li><li id="hl0002980"><span class="list-item-label">▪</span><p id="hl0002982">St. Jude Medical <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0002985" class="table-align-"  >None</td><td id="hl0002986" class="table-align-"  >None</td><td id="hl0002987" class="table-align-"  >None</td></tr><tr><td id="hl0002989" class="table-align-"  >Sami Viskin</td><td id="hl0002990" class="table-align-"  >Content Reviewer</td><td id="hl0002991" class="table-align-"  >Tel Aviv Medical Center—Department of Cardiology</td><td id="hl0002992" class="table-align-"  ><ul id="hl0002993"><li id="hl0002994"><span class="list-item-label">▪</span><p id="hl0002996">Boston Scientific European Strategy Advisory Board</p></li></ul></td><td id="hl0002997" class="table-align-"  >None</td><td id="hl0002998" class="table-align-"  >None</td><td id="hl0002999" class="table-align-"  >None</td><td id="hl0003000" class="table-align-"  >None</td><td id="hl0003001" class="table-align-"  >None</td><td id="hl0003002" class="table-align-"  >None</td></tr><tr><td id="hl0003004" class="table-align-"  >Samuel S. Gidding</td><td id="hl0003005" class="table-align-"  >Content Reviewer—ACC/AHA Task Force on Clinical Practice Guidelines</td><td id="hl0003006" class="table-align-"  >Dupont Hospital for Children—Nemours Cardiac Center</td><td id="hl0003007" class="table-align-"  ><ul id="hl0003008"><li id="hl0003009"><span class="list-item-label">▪</span><p id="hl0003011">Familial Hypercholesterolemia Foundation <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li><li id="hl0003013"><span class="list-item-label">▪</span><p id="hl0003015">Regenxbio</p></li></ul></td><td id="hl0003016" class="table-align-"  >None</td><td id="hl0003017" class="table-align-"  >None</td><td id="hl0003018" class="table-align-"  ><ul id="hl0003019"><li id="hl0003020"><span class="list-item-label">▪</span><p id="hl0003022">Familial Hypercholestrolemia Foundation <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li><li id="hl0003024"><span class="list-item-label">▪</span><p id="hl0003026">NIH Grants <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0003029" class="table-align-"  ><ul id="hl0003030"><li id="hl0003031"><span class="list-item-label">▪</span><p id="hl0003033">Cardiology Division Head <a class="inline-reference" href="#dtbl2fndagger">†</a></p></li></ul></td><td id="hl0003035" class="table-align-"  >None</td><td id="hl0003036" class="table-align-"  >None</td></tr><tr><td id="hl0003038" class="table-align-"  >Silvia G. Priori</td><td id="hl0003039" class="table-align-"  >Content Reviewer</td><td id="hl0003040" class="table-align-"  >Professore Ordinario di Cardiologia—Università di Pavia—Direttore Scientifico—Istituti Clinici Scientifici Maugeri—Pavia, Italia</td><td id="hl0003041" class="table-align-"  ><ul id="hl0003042"><li id="hl0003043"><span class="list-item-label">▪</span><p id="hl0003045">Ambry Genetics</p></li><li id="hl0003046"><span class="list-item-label">▪</span><p id="hl0003048">Boston Scientific</p></li><li id="hl0003049"><span class="list-item-label">▪</span><p id="hl0003051">Medtronic</p></li><li id="hl0003052"><span class="list-item-label">▪</span><p id="hl0003054">Medtronic, Inc.</p></li></ul></td><td id="hl0003055" class="table-align-"  >None</td><td id="hl0003056" class="table-align-"  ><ul id="hl0003057"><li id="hl0003058"><span class="list-item-label">▪</span><p id="hl0003060">Audentes Therapeutics Inc <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0003063" class="table-align-"  ><ul id="hl0003064"><li id="hl0003065"><span class="list-item-label">▪</span><p id="hl0003067">Gilead Sciences <a class="inline-reference" href="#dtbl2fnlowast"><sup>∗</sup></a></p></li></ul></td><td id="hl0003070" class="table-align-"  ><ul id="hl0003071"><li id="hl0003072"><span class="list-item-label">▪</span><p id="hl0003074">HRS</p></li><li id="hl0003075"><span class="list-item-label">▪</span><p id="hl0003077">GS-US-372-1234 <a class="inline-reference" href="#dtbl2fnddagger">‡</a></p></li></ul></td><td id="hl0003079" class="table-align-"  >None</td><td id="hl0003080" class="table-align-"  >None</td></tr><tr><td id="hl0003082" class="table-align-"  >Susan Strong</td><td id="hl0003083" class="table-align-"  >Official Reviewer—AHA</td><td id="hl0003084" class="table-align-"  >Sabin Middle School</td><td id="hl0003085" class="table-align-"  >None</td><td id="hl0003086" class="table-align-"  >None</td><td id="hl0003087" class="table-align-"  >None</td><td id="hl0003088" class="table-align-"  >None</td><td id="hl0003089" class="table-align-"  >None</td><td id="hl0003090" class="table-align-"  >None</td><td id="hl0003091" class="table-align-"  >None</td></tr><tr><td id="hl0003093" class="table-align-"  >Win-Kuang Shen</td><td id="hl0003094" class="table-align-"  >Content Reviewer</td><td id="hl0003095" class="table-align-"  >Professor of Medicine—Consultant—Mayo Clinic Arizona, Phoenix Campus</td><td id="hl0003096" class="table-align-"  >None</td><td id="hl0003097" class="table-align-"  >None</td><td id="hl0003098" class="table-align-"  >None</td><td id="hl0003099" class="table-align-"  >None</td><td id="hl0003100" class="table-align-"  >None</td><td id="hl0003101" class="table-align-"  >None</td><td id="hl0003102" class="table-align-"  >None</td></tr><tr><td id="hl0003104" class="table-align-"  >Zachary D. Goldberger</td><td id="hl0003105" class="table-align-"  >Official Reviewer—ACC/AHA Task Force on Clinical Practice Guidelines Lead Reviewer</td><td id="hl0003106" class="table-align-"  >Assistant Professor of Medicine—Division of Cardiology—Harborview Medical Center—University of Washington School of Medicine</td><td id="hl0003107" class="table-align-"  ><ul id="hl0003108"><li id="hl0003109"><span class="list-item-label">▪</span><p id="hl0003111">RubiconMD</p></li></ul></td><td id="hl0003112" class="table-align-"  >None</td><td id="hl0003113" class="table-align-"  >None</td><td id="hl0003114" class="table-align-"  >None</td><td id="hl0003115" class="table-align-"  >None</td><td id="hl0003116" class="table-align-"  >None</td><td id="hl0003117" class="table-align-"  >None</td></tr></tbody></table></div><div class="inline-table-caption">This table represents the relationships of reviewers with industry and other entities that were disclosed at the time of peer review, including those not deemed to be relevant to this document, at the time this document was under review. The table does not necessarily reflect relationships with industry at the time of publication. A person is deemed to have a significant interest in a business if the interest represents ownership of ≥5% of the voting stock or share of the business entity, or ownership of ≥$5000 of the fair market value of the business entity; or if funds received by the person from the business entity exceed 5% of the person’s gross income for the previous year. Relationships that exist with no financial benefit are also included for the purpose of transparency. Relationships in this table are modest unless otherwise noted. Names are listed in alphabetical order within each category of review. Please refer to <a id="hl0003120" href="http://www.acc.org/guidelines/about-guidelines-and-clinical-documents/relationships-with-industry-policy" target="_blank">http://www.acc.org/guidelines/about-guidelines-and-clinical-documents/relationships-with-industry-policy</a> for definitions of disclosure categories or additional information about the ACC/AHA Disclosure Policy for Writing Committees. </div><div class="inline-table-caption">ABIM indicates American Board of Internal Medicine; ACC, American College of Cardiology; ACGME, Accreditation Council for Graduate Medical Education; AHA, American Heart Association; ARTESiA, Apixaban for the Reduction of Thrombo-Embolism in Patients With Device-Detected Sub-Clinical Atrial Fibrillation; BEAT-HF, Better Effectiveness After Transition–Heart Failure DSMB, data safety monitoring board; ENDEAVOUR, carfilzomib and dexamethasone versus bortezomib and dexamethasone for patients with relapsed or refractory multiple myeloma; EP, electrophysiology; FDA, U.S. Food and Drug Administration; HFSA, Heart Failure Society of America; HRS, Heart Rhythm Society; ICD, implantable cardioverter-defibrillator; JACC, Journal of the American College of Cardiology; NIH, National Institutes of Health; NHLBI, National Heart, Lung, and Blood Institute; and PACE, Programs of All-Inclusive Care for the Elderly.</div><ul class="table-footnotes"><li id="hl0003122"><a id="dtbl2fndagger"></a><span class="superscript-reference">†</span>No financial benefit.</li><li id="hl0003125"><a id="dtbl2fnddagger"></a><span class="superscript-reference">‡</span>This disclosure was entered under the Clinical Trial Enroller category in the ACC’s disclosure system. To appear in this category, the author acknowledges that there is no direct or institutional relationship with the trial sponsor as defined in the ACC/AHA Disclosure Policy for Writing Committees.</li><li id="hl0003128"><a id="dtbl2fnlowast"></a><span class="superscript-reference">∗</span>Significant relationship.</li></ul></div>',
	errorMessage: "",
};
