export const longText =`<div class="lewis-carroll"><h2>Alice in Wonderlnad</h2><span class="AliceIpsumLocation"><p></p>‘I’ve heard something like it,’ said Alice.<p></p>‘Idiot!’ said the Queen, tossing her head impatiently; and, turning to Alice, she went on, ‘What’s your name, child?’<p></p>‘Once upon a time there were three little sisters,’ the Dormouse began in a great hurry; ‘and their names were Elsie, Lacie, and Tillie; and they lived at the bottom of a well--’<p></p>‘Well, then,’ the Cat went on, ‘you see, a dog growls when it’s angry, and wags its tail when it’s pleased. Now I growl when I’m pleased, and wag my tail when I’m angry. Therefore I’m mad.’<p></p>‘I have answered three questions, and that is enough,’ /
Said his father; ‘don’t give yourself airs! /
Do you think I can listen all day to such stuff? /
Be off, or I’ll kick you down stairs!’<p></p>‘Then the Dormouse shall!’ they both cried. ‘Wake up, Dormouse!’ And they pinched it on both sides at once.<p></p>She drew her foot as far down the chimney as she could, and waited till she heard a little animal (she couldn’t guess of what sort it was) scratching and scrambling about in the chimney close above her: then, saying to herself ‘This is Bill,’ she gave one sharp kick, and waited to see what would happen next.<p></p>Very soon the Rabbit noticed Alice, as she went hunting about, and called out to her in an angry tone, ‘Why, Mary Ann, what ARE you doing out here? Run home this moment, and fetch me a pair of gloves and a fan! Quick, now!’ And Alice was so much frightened that she ran off at once in the direction it pointed to, without trying to explain the mistake it had made.<p></p>“Twinkle, twinkle, little bat!/
 How I wonder what you’re at!”<p></p>Alice considered a little, and then said ‘The fourth.’<p></p>And she went on planning to herself how she would manage it. ‘They must go by the carrier,’ she thought; ‘and how funny it’ll seem, sending presents to one’s own feet! And how odd the directions will look!<p></p>‘But she must have a prize herself, you know,’ said the Mouse.<p></p>‘--or next day, maybe,’ the Footman continued in the same tone, exactly as if nothing had happened.<p></p>‘By-the-bye, what became of the baby?’ said the Cat. ‘I’d nearly forgotten to ask.’<p></p>She drew her foot as far down the chimney as she could, and waited till she heard a little animal (she couldn’t guess of what sort it was) scratching and scrambling about in the chimney close above her: then, saying to herself ‘This is Bill,’ she gave one sharp kick, and waited to see what would happen next.<p></p>‘I don’t know what you mean,’ said Alice.<p></p>‘It IS a long tail, certainly,’ said Alice, looking down with wonder at the Mouse’s tail; ‘but why do you call it sad?’ And she kept on puzzling about it while the Mouse was speaking, so that her idea of the tale was something like this:--<p></p>‘But she must have a prize herself, you know,’ said the Mouse.<p></p>‘I didn’t mean it!’ pleaded poor Alice. ‘But you’re so easily offended, you know!’<p></p>‘Why not?’ said the March Hare.</span></div>`;
 export const shortText =`<div class="lewis-carroll AliceIpsumLocation">
 <h2>I don’t know of any that do</h2> 
 <p>Alice said very politely, feeling quite pleased to have got into a conversation.</p>
 <p><strong>‘The first thing I’ve got to do,’</strong> said Alice to herself, as she wandered about in the wood, ‘is to grow to my right size again; and the second thing is to find my way into that lovely garden. I think that will be the best plan.’</p></div>`;

 export const mediumText= `<p>‘They lived on treacle,’ said the Dormouse, after thinking a minute or two.</p>
 <p>The executioner’s argument was, that you couldn’t cut off a head unless there was a body to cut it off from: that he had never had to do such a thing before, and he wasn’t going to begin at HIS time of life.</p>
 <p>Alice caught the baby with some difficulty, as it was a queer-shaped little creature, and held out its arms and legs in all directions, ‘just like a star-fish,’ thought Alice. The poor little thing was snorting like a steam-engine when she caught it, and kept doubling itself up and straightening itself out again, so that altogether, for the first minute or two, it was as much as she could do to hold it.</p>`;